### PR TITLE
Enable IPV6 connections

### PR DESCRIPTION
**Pull request by crwolff**
Patch based on 'Echo client program' [Example](https://docs.python.org/3/library/socket.html#example)

### CODE REVIEW

**Comment by greenbender** [comment]
It's been a while since I looked at this code. IPv6 support sounds like a good idea.

However, I'd be tempted to implement it using `socket.create_connection()` and `ssl.SSLContext.wrap_socket()` to simplify the implementation. lmk if you would  be happy to implement it that way - I can do this if otherwise, but not right away.

**Comment by crwolff** [comment]
Unfortunately, I don't have access to an IPV6 system at the moment so I can't test a different solution.

**Comment by greenbender** [comment]
I have just made this change. I'll push to pypi soon, but ferel free to try it out.

**Comment by crwolff** [comment]
The patch is giving a ValueError in the SSl wrapper.

  File "./Program", line 44, in worker
    NC = nntp.NNTPClient(cfg['Server']['Server'], int(cfg['Server']['Port']),
  File "/home/user/.local/lib/python3.8/site-packages/nntp/nntp.py", line 532, in __init__
    super(NNTPClient, self).__init__(
  File "/home/user/.local/lib/python3.8/site-packages/nntp/nntp.py", line 156, in __init__
    self.socket = context.wrap_socket(self.socket)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by greenbender** [comment]
Thanks for catching that. I don't have a usenet account to test with at the moment. I checked IPv6 worked but not ssl. My bad.

**Comment by greenbender** [comment]
Fixed
 *  `1.0.3` yanked from pypi
 *  `1.0.4` pushed to pypi

**Pull request closed without merging**
